stages:
  data_ingestion:
    cmd: python src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CNN_Classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chicken-fecal-images

  prepare_base_model:
    matrix:
      include:
        - {}
    cmd: python src/CNN_Classifier/pipeline/stage_02_prepare_base_model.py
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES 
      - LEARNING_RATE
    deps:
      - src/CNN_Classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    outs:
      - artifacts/prepare_base_model

  training:
    matrix:
      include:
        - {}
    cmd: python src/CNN_Classifier/pipeline/stage_03_training.py
    deps:
      - src/CNN_Classifier/pipeline/stage_03_training.py
      - src/CNN_Classifier/components/prepare_callback.py
      - config/config.yaml
      - artifacts/data_ingestion/Chicken-fecal-images
      - artifacts/prepare_base_model
    params:
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5

  evaluation:
    matrix:
      include:
        - {}
    cmd: python src/CNN_Classifier/pipeline/stage04_evaluation.py
    deps:
      - src/CNN_Classifier/pipeline/stage04_evaluation.py
      - config/config.yaml
      - artifacts/training/model.h5
      - artifacts/data_ingestion/Chicken-fecal-images
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json: {cache: false} 
        
        
        



